config/routes.rb
Rails.application.routes.draw do
  get 'reputation/update'

  devise_for :users
  resources :playlists
  resources :selections, only: :destroy
  match '/reputations/:song_id' => 'reputations#update', via: [:put, :patch], as: :reputation

  root 'search#index'
end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
  belongs_to :user
  has_many :selections
  has_many :songs, through: :selections

  def add_song(song)
    position = self.selections.maximum(:position).to_i + 1
    self.selections.create(position: position, song: song)
  end
end

app/models/selection.rb
class Selection < ActiveRecord::Base
  belongs_to :playlist
  belongs_to :song
  default_scope  { order(position: :asc)}
end

app/models/song.rb
class Song < ActiveRecord::Base
  default_scope { order(reputation: :desc) }
  has_many :playlists

  def self.from_remote(query, remote=GimmeKaraoke::SongQuery)
    songs = remote.search(query)
    return nil unless songs
    s = songs.map do |song|
      attrs = {uid: song.uid}
      Song.where(attrs).first_or_create(song.attributes)
    end.sort_by{|s| -s.reputation}
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :playlists
  has_many :selections, through: :playlists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :authenticate_user!
end

app/controllers/concerns/selections_controller.rb
class SelectionsController < ApplicationController
  def destroy
    selection = current_user.selections.find_by(id: params[:id])
    selection.destroy if selection

    render nothing: true
  end
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  def show
    @playlist = current_user.playlists.find params[:id]
    @current_selection = @playlist.selections.find_by(id: params[:selection_id]) ||
      @playlist.selections.first
    respond_to do |format|
      format.html
      format.json {render 'playlist'}
    end
  end

  def update
    @song = Song.find_by uid: params[:song]
    @playlist = current_user.playlists.find params[:id]
    @playlist.add_song @song

    respond_to do |format|
      format.json {render 'playlist'}
    end
  end
end

app/controllers/reputations_controller.rb
class ReputationsController < ApplicationController
  def update
    @song= Song.find(params[:song_id])
    @song.update(reputation: @song.reputation + 1)
    render nothing: true
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  skip_filter :authenticate_user!
  def index
    if params[:q]
      @query = params[:q]
      if signed_in?
        @playlist = current_user.playlists.first_or_create(name: "Now Playing")
      else
        @playlist = OpenStruct.new
      end
      @results = Song.from_remote(params[:q])
      render :show
    end
  end
end

app/controllers/selections_controller.rb
class SelectionsController < ApplicationController
  def destroy
    selection = current_user.selections.find_by(id: params[:id])
    if selection
      selection.destroy
      render json: selection.id
    else
      render nothing: true
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def notices
    notice_bar + alert_bar
  end
  
  def alert_for(type)
    content_tag(:p, class: "alert alert-#{type}" ) do
      content_tag(:button, class: 'close', "data-dismiss" => 'alert') do
        content_tag(:span, "&times;".html_safe)
      end +
      yield
    end
  end

  def notice_bar
    if notice
      alert_for(:success) do
        notice
      end
    end.to_s.html_safe
  end

  def alert_bar
    if alert
      alert_for(:danger) do
        alert
      end
    end.to_s.html_safe
  end
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
  def element_for_selection(selection, index)
    song = selection.song
    link_to "?selection_id=#{selection.id}", class: 'song-title' do
      content_tag(:div) do
        image_tag(song.thumbnails.first, class: 'img-responsive')
      end +
      "#{index}. #{selection.song.title}" +
      content_tag(:div) do
        link_to "Remove from Playlist", selection, remote: true, method: :delete, class: 'remove-from-playlist'
      end +
      content_tag(:div) do
        link_to "Love this song!", reputation_path(song_id: selection.song.id), method: :patch, remote: true
      end
    end.html_safe
  end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>KaraAwesome</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body class='container'>
  <div>
    <%= link_to "KaraAwesome", root_path %>
  </div>
  <% if signed_in? %>
  <%= link_to "My Playlist", current_user.playlists.first %> | <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
  <% else %>
  <%= link_to "Sign in", new_user_session_path %> or <%= link_to "Sign up", new_user_registration_path %> To create an awesome playlist
  <% end %>
  <p class="alerts"><%= notices %></p>

  <%= yield %>

</body>
</html>

app/views/playlists/show.html.erb
<div class="row">
  <div class="col-xs-12">
    <div data-current-id='<%= @current_selection.song.uid %>' id="player"></div>
  </div>

  <% @playlist.selections.each.with_index(1) do |selection, i| %>
  <div data-id='<%= selection.id %>' class="col-xs-6">
    <%= element_for_selection(selection, i) %>
  </div>
  <% end %>
</div>

app/views/search/_results.html.erb
<section class="row">
  <% results.each do |result| %>
  <article class='col-xs-6 col-md-3'>
    <header class='song-title'><%= link_to result.title, result.url %></header>
    Song reputation: <%= result.reputation %>
    <%= image_tag result.thumbnails.first %>
    <%= link_to "Add to playlist #{@playlist.name}", playlist_path(@playlist, song: result.uid), method: :patch, remote: true, class: "add-to-playlist" %>
  </article>
  <% end %>
</section>

app/views/search/index.html.erb
<h1>Welcome to KaraAwesome</h1>
<%= form_tag root_path, method: :get, class: "search" do %>
<fieldset>
  <legend>Find awesome Karaoke songs</legend>
  <%= label_tag :q, "Enter your query" %>
  <%= text_field_tag :q %>
  <%= submit_tag "Get awesomeness", class: 'btn btn-success' %>
</fieldset>
<% end %>

app/views/search/show.html.erb
<h1>Search Results for: <%= @query %></h1>
<% if signed_in? %>
  <%= link_to "Playlist", @playlist %>
<% end %>

<%= form_tag root_path, method: :get, class: "search" do %>
<fieldset>
  <legend></legend>
  <%= label_tag :q, "Search again" %>
  <%= text_field_tag :q %>
  <%= submit_tag "Get awesomeness", class: "btn btn-success" %>
</fieldset>
<% end %>
<% if @results %>
  <%= render partial: 'results', locals: {results: @results} %>
<% else %>
  No results for "<%= @query %>". Try again?
<% end %>